### PR TITLE
R bush/ruler tweaks

### PR DESCRIPTION
**Pull request by awilkey**
@adf-ncgr ignore prior pull request, wrong branch. 
Implement Ruler as-a-scroll bar and "box zoom"

### CODE REVIEW

**Comment by awilkey** [comment]
@adf-ncgr Panning in the area of the ruler will pan the view up and down. click and drag not starting over the ruler and instead it  turns into a "box zoom".

**Comment by adf-ncgr** [comment]
@awilkey- initial impression very favorable;  look forward to tomorrow's 
discussion...

**Comment by adf-ncgr** [comment]
@awilkey: minor point regarding UI (mostly note to self for tomorrow's call); after one has box-zoomed once, I would have expected that another rectangle select on the ruler would simply move the view to that new outlined region (ie a drag-select on the ruler would always just replace the current zoom and pan with whatever you had outlined)- this appears not to be the case at the moment- possibly the behavior is intentional and I'm just not getting it, but let's discuss tomorrow and decide what makes sense (unless you can actually understand what I've just written, agree, and want to go ahead and make the change, which I imagine will be easy given what you've already accomplished).

**Comment by adf-ncgr** [comment]
@awilkey- do you want me to go ahead and merge this or would it make more sense to wait until you get time to work on the separating of the pan/zoom events as we discussed this morning? either way works for me.

**Comment by awilkey** [comment]
@adf-ncgr Go ahead and merge, separating out would involve figuring out how to introduce new UI components and as such is a bit on the time-intensive side.

**Comment by adf-ncgr** [comment]
@awilkey- sounds good; unless you object within the next 15 minutes I will probably just add those tweaks regarding the map_stop updating into this branch and let them come along for the ride.

**Pull request merged**
