### PR TITLE
Feature/tweaks

### PR DESCRIPTION
**Pull request by awilkey**
@adf-ncgr Ok, this should be fix several of the issues discussed, though not entirely certain if the font load-in has been completely fixed (though local and remote testing implies it should be, has never been a very reliable issue to duplicate on my end). Box-select behavior has been changed to zoom if boxed on ruler, or info-popup if boxed on anything else, though the box is still basic and could really use a pass of sorting/ display reconfiguration.

### CODE REVIEW

**Comment by adf-ncgr** [comment]
one oddity to note- rectangle select is working if you drag from upper to lower but not from lower to upper; probably just need to switch bounds coordinates somewhere?

**Comment by adf-ncgr** [comment]
minor suggestion- if easy, would probably be good to order the elements (e.g. markers) that are
displayed in the popover by the order of their position on the map. at least for point-like objects, this should help the user grok the info more easily when they get more markers in the popover than are labelled at the current zoom level. for extended objects (e.g. QTLs), it probably doesn't matter as much but maybe just ordering by start position to be somewhat consistent (could also imagine ordering by midpoint, but not sure that would be more helpful for any reason).

**Comment by awilkey** [comment]
@adf-ncgr The box select should be working as intended now. A bunch of small things changed, so tests are probably going to fail, but nothing massive seems to be failing at user-level. As this is a "get it out" pull I haven't updated the tests to reflect the changes yet. Nothing that fails is critical.

**Comment by adf-ncgr** [comment]
OK, got the quick box-select fix (thanks!) and also verified that the earlier font issues seem to be working well in the other browsers. The thing about the ordering of elements in the popover is definitely not critical for this alpha release, but let me know if you think it is trivial enough to just knock it out, otherwise I'll submit it as an enhancement for later on.

**Comment by adf-ncgr** [comment]
looks like you just knocked it out. will have a look.

**Comment by adf-ncgr** [comment]
looks good to me! thanks...

**Pull request merged**
