### PR TITLE
Feature/ui improvements various

### PR DESCRIPTION
**Pull request by guidorice**
This PR includes UI tools for Reset View, Add Map, and Remove Map. Before additional UI tools can be added, e.g. a Filter tool, first more groundwork needs to be done on the configuration file and
json schema.

### CODE REVIEW

**Comment by adf-ncgr** [comment]
@guidorice current behavior of reset view seems to be altering map selection back to initial view (ie any maps added are removed); I thought we had provisionally decided that the reset view would only affect zoom-pan and that reset of maps included in display was easily effected via page reload- did you change your thinking on that?

**Comment by guidorice** [comment]
@adf-ncgr no I did not change my thinking- it must be a bug, I will look into that and get a fix into this branch.

**Comment by guidorice** [comment]
@adf-ncgr ok fixed.

**Comment by adf-ncgr** [comment]
@guidorice I think something is still a little off; if I add some maps, then reset view things look OK but then if I add more maps the originally added maps seem to disappear? Also, the individual map zooms are retained- maybe that is by design (haven't thought too much about it, but my sense is that the average user might expect+/desire each map zoom to reset as well- could be convinced otherwise)

**Comment by guidorice** [comment]
@adf-ncgr yes you are right, there appears to be a bigger bug with the application state getting reset. Thanks for catching this. I will re-open another PR when this is resolved. 

re: the individidual map zoom levels, are not reset, that is not implemented yet. I will need to coordinate with @awilkey on that, or he can implement it in BioMap class and/or other classes.

**Comment by guidorice** [comment]
@adf-ncgr OK I think we can move forward with this merge now, hopefully.

**Comment by awilkey** [comment]
@guidorice @adf-ncgr Will merge  into current working RBush/* branch and implement reset behavior on local zoom once this merge is done.

**Comment by adf-ncgr** [comment]
@awilkey I did the merge a little while ago, but just occurred to me you 
may not have gotten notified;
anyway, it's all yours...

**Comment by awilkey** [comment]
@adf-ncgr has been resolved in recent pushes to QTL branch. Will submit a pull request either this evening or first thing tomorrow morning after adding QTL track hit detection as part of popup.

**Comment by adf-ncgr** [comment]
@awilkey sounds good; tomorrow is fine, no need to rush it on my account
(although will be happy to give it some attention whenever you make the 
request...)

**Pull request merged**
